### ISSUE TITLE
JsonDataException when deleting articles

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/android-app#646]
Since Wallabag 2.0.2 I see errors when deleting articles using the app: 

![screenshot_2017-10-26-23-48-47-076](https://user-images.githubusercontent.com/226063/32147942-aba4b5b4-bcef-11e7-8b4f-c2a2f9479c17.jpeg)

This error does not seem to affect the actual deletion of the article.

Android 6.0.1 / Wallabag _master_ (formerly 2.3 branch)

**Comment by Strubbl** [comment]
Yes, same error here with the same app and server version

**Comment by Kdecherf** [comment]
After a quick test, it seems that the uid and id fields from original entry are lost just after the Doctrine flush:
https://github.com/wallabag/wallabag/blob/master/src/Wallabag/ApiBundle/Controller/EntryRestController.php#L562-L564

**Comment by Kdecherf** [comment]
Sadly, the issue is still present with my fix released in wallabag 2.3.1

**Comment by techexo** [comment]
I have the same issue following the upgrade to the last release version of wallabag (2.3.2). My wallabag is self-hosted on Debian/nginx with HTTP/2 support. I will try to see what's going on in the logs asap.

**Comment by techexo** [comment]
Any news on this issue? It is quite annoying to see the error each time an article is deleted from the app.
Please tell me if there is something I could provide to help solve this problem. Thanks

**Comment by Strubbl** [comment]
Do you see any error in the var/logs/prod.log of the wallabag server?

**Comment by techexo** [comment]
When I try to delete on my phone an article with the app, I have the error mentioned above in a notification, and the following message in `var/logs/prod.log`:
> [2018-03-19 08:03:37] request.INFO: Matched route "api_delete_entries". {"route":"api_delete_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::deleteEntriesAction","_format":"json","entry":"964","_route":"api_delete_entries"},"request_uri":"https://wallabag.anbuco.fr/api/entries/964.json","method":"DELETE"} []
[2018-03-19 08:03:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Wallabag\CoreBundle\Entity\Entry object not found." at /var/www/wallabagv2/vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php line 66 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Wallabag\\CoreBundle\\Entity\\Entry object not found. at /var/www/wallabagv2/vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php:66)"} []

**Comment by Strubbl** [comment]
"Uncaught PHP Exception" looks like an entirely server error. Do you have any idea how we can fix this in the app itself without working around it? 

Meanwhile i am opening an issue in the core repository so that it is going to be fixed in the API soon™

**Comment by di72nn** [comment]
Isn't that "NotFound" error happens only when app tries to retry the removal (after the first one failed on the client side because of the `null` id)?

**Comment by Strubbl** [comment]
No, i added an URL via web app. Then synced my Android app and deleted that article via app. Got the same error

**Comment by techexo** [comment]
Since I updated my phone, I cannot reproduce the bug anymore... No modifications were made on the server. Strange!

**Comment by linusboyle** [comment]
Still no luck and have this problem too. It does not affect me much, though

**Comment by techexo** [comment]
@linusboyle Have you tried deleting the cache of the app (via the application informations on Android) then doing a full synchronization of the articles?

**Comment by oupala** [comment]
Same problem here. Wallabag app have been downloaded from F-Droid, it is version 2.0.2 (106) of Wallabag app.

**Comment by Strubbl** [comment]
@oupala
Is this problem still existing with Version 2.1.0 (109)? It is available with fdroid.

**Comment by Strubbl** [comment]
@Kdecherf Can you confirm this issue is fixed? Have you tried it?

**Comment by Kdecherf** [comment]
@Strubbl yep, the PR has been applied on my instance, the issue does not show up since then.

**Comment by oupala** [comment]
@Strubbl I'm now using version 2.1.0 (109) from F-Droid and I still have the same error on android.

**Comment by Strubbl** [comment]
This issue should be fixed with the next wallabag server release. See
* https://github.com/wallabag/wallabag/issues/3711
* https://github.com/wallabag/wallabag/pull/3887
* https://github.com/wallabag/wallabag/milestone/63

So if that wallabag server version gets released, this issue should not occur in the app anymore - even without an app update.

**Comment by oupala** [comment]
Ok, I understand the problem was on the server side. Thanks for the information.
